[Travis] caskroom is deprecated
Reinstall of Java failed with:

==> Downloading http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_osx-x64_bin.dmg
Error: undefined method `undent' for #<String:0x000000010233a010>

Hope this fixes it

Signed-off-by: Stefan Marr <git@stefan-marr.de>